const { Router } = require('express')
const router = Router()
const controller = require('./controller')
router
  .use('/proxy', controller.proxy)
  .use('/sockjs-node', controller.proxy)
  .get('/install', controller.install)
  .get('/auth', controller.auth)
  .get('/installChatBot', controller.installChatBot)
  .get('/authChatBot', controller.authChatBot)
  .get('/home', controller.home)
  .get('/authorize', controller.inClientAuthorize)
  .get('/getEngagementInfo', controller.getEngagementInfo)
  .post('/onauthorized', controller.inClientOnAuthorized)
  .get('/installHubspot', controller.installHubSpot)
  .get('/hubspotOauthCallback', controller.hubspotOauthCallback)
  .get('/isCrmInstalled', controller.getCrmInstalled)
  .post('/getCrmContactByPhone', controller.getCrmContactsByPhone)
  .get('/getEngagementDetails', controller.getEngagementDetails)
  .post('/incomingEngagement', controller.storeEngagementDetails)
  .post('/createCrmTicket', controller.createCrmTicket)
  .post('/saveEngagementNotes', controller.saveEngagementNotes)
  .post('/getCrmTickets', controller.getCrmTickets)
  .post('/updateCrmTicket', controller.updateCrmTicket)
  .get('/getCrmAccountInfo', controller.getCrmAccountInfo)
  .post('/searchRelatedToRecords', controller.searchRelatedToRecords)
  .post('/createCrmContact', controller.createCrmContact)
  .post('/searchCrmContacts', controller.searchCrmContacts)
  .post('/updateCrmContact', controller.updateCrmContact)
  .get('/sendTestMessage', controller.sendChatBotMessage)

module.exports = router
